#!/usr/bin/env python3

import yaml
import fileinput


def traverse(d, prefix):
    # print("# %s => %s" % (type(d), prefix))
    if isinstance(d, dict):
        for k, v in d.items():
            if '.' in k:
                k = '"%s"' % k
            traverse(v, prefix + '.' + k)
    elif isinstance(d, list):
        i = 0
        for v in d:
            traverse(v, "%s[%d]" % (prefix, i))
            i += 1
    else:
    # if isinstance(d, str) or isinstance(d, int) or isinstance(d, bool):
        print(prefix + "=" + str(d))


f = ""
for l in fileinput.input():
    f += l

y_all = list(yaml.load_all(f))
f = None
for y in y_all:
    print("---")
    traverse(y, '')
